CREATE DATABASE ABC
GO 
USE ABC
GO

CREATE TABLE SINHVIEN
(
	MASV CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(60),
	NGAYSINH SMALLDATETIME,
)

CREATE TABLE LOP
(
	MALOP VARCHAR(7) NOT NULL,
	TENLOP VARCHAR(30) NOT NULL,
)

-- SỬA ĐỔI CẤU TRÚC BẢNG 
ALTER TABLE LOP ADD CONSTRAINT PK_LOP PRIMARY KEY (MALOP) 
-- THÊM CỘT
ALTER TABLE SINHVIEN ADD DIACHI VARCHAR(100)
-- SỬA ĐỔI THUỘC TÍNH COLUMN 
ALTER TABLE SINHVIEN ALTER COLUMN HOTEN VARCHAR(60) NOT NULL
-- THÊM CỘT VÀO BẢNG 
ALTER TABLE SINHVIEN ADD MALOP VARCHAR(7)
-- TẠO KHÓA NGOẠI CHO BẢNG
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SV_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP) 
-- THÊM CỘT TRUONGLOP CHO BẢNG LỚP
ALTER TABLE LOP ADD TRGLOP CHAR(5)
-- TẠO KHÓA NGOẠI CHO BẢNG LỚP 
ALTER TABLE LOP ADD CONSTRAINT FK_LOP_SV FOREIGN KEY (TRGLOP) REFERENCES SINHVIEN (MASV)

CREATE TABLE MONHOC
(
	MAMH CHAR(8),
	TENMH VARCHAR(20)
)
ALTER TABLE MONHOC ALTER COLUMN MAMH CHAR(8) NOT NULL 
ALTER TABLE MONHOC ADD CONSTRAINT PK_MONHOC PRIMARY KEY (MAMH) 
ALTER TABLE MONHOC ADD CONSTRAINT UQ_TENMH UNIQUE (TENMH)

CREATE TABLE THI
(
	MASV CHAR(5) NOT NULL,
	MAMH CHAR(8) NOT NULL,
	DIEM INT
)
-- TẠO KHÓA CHÍNH CHO BẢNG 
ALTER TABLE THI ADD CONSTRAINT PK_THI PRIMARY KEY (MASV, MAMH)
-- TẠO KHÓA NGOẠI CHO THI VOI MONHOC 
ALTER TABLE THI ADD CONSTRAINT FK_THI_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC (MAMH)
ALTER TABLE THI ADD CONSTRAINT FK_THI_SV FOREIGN KEY (MASV) REFERENCES SINHVIEN (MASV)
-- SỬA ĐỔI THUỘC TÍNH CHO BẢNG
ALTER TABLE SINHVIEN ALTER COLUMN DIACHI VARCHAR(80)
-- XÓA CỘT 
ALTER TABLE SINHVIEN DROP COLUMN DIACHI
-- XÓA RÀNG BUỘC 
ALTER TABLE THI DROP CONSTRAINT FK_THI_MONHOC 
-- XÓA BẢNG (PHẢI XÓA KHÓA NGOẠI TRƯỚC)
DROP TABLE SINHVIEN 
-- XÓA DATABASE 
DROP DATABASE ABC 
-- THÊM DỮ LIỆU CHO BẢNG
INSERT INTO SINHVIEN VALUES ('1', 'HELEN', '24-09-2000', NULL)
SET DATEFORMAT DMY
INSERT INTO SINHVIEN VALUES ('2','HANA','23-07-2000',NULL)
INSERT INTO SINHVIEN (MASV, HOTEN) VALUES ('3', 'JOHN')
UPDATE SINHVIEN SET HOTEN = 'SARAH', NGAYSINH = '20-09-2000'
WHERE MASV = '2' -- ĐIỀU KIỆN ĐỂ XÓA 

DELETE SINHVIEN WHERE MASV = 'I'

SELECT * FROM SINHVIEN 

